### ISSUE TITLE
why?

### ISSUE THREAD

**Issue by matin12821** [Dellenoam/NotPixelBot#13]
![Capture](https://github.com/user-attachments/assets/90b40514-10f0-478e-b7cb-0d9eb26b1716)

**Comment by Dellenoam** [comment]
read README first...

**Comment by Dellenoam** [comment]
you don't have nodejs installed

**Comment by Rio46-org** [comment]
Don't increase point to paint

**Comment by Dellenoam** [comment]
Open a new issue. This one is done

**Comment by Rio46-org** [comment]
![Uploading P_20241130_231352.jpg…]()
