### ISSUE TITLE
ISSUE $1

### ISSUE THREAD

**Issue by cryptoknightsz** [Dellenoam/NotPixelBot#20]
![image](https://github.com/user-attachments/assets/66b0439b-89c6-478e-97a6-91c22e370a2b)
Almost wasted my 39 account paint as 90% paint failed

**Comment by deyman12** [comment]
> ![image](https://private-user-images.githubusercontent.com/67500412/391465866-66b0439b-89c6-478e-97a6-91c22e370a2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMzUwODEsIm5iZiI6MTczMzEzNDc4MSwicGF0aCI6Ii82NzUwMDQxMi8zOTE0NjU4NjYtNjZiMDQzOWItODljNi00NzhlLTk3YTYtOTFjMjJlMzcwYTJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDEwMTk0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhMDgwMjY5ODAwMWE2NDgwZGM0MTBhYzNkOTUzY2I2Mjg2YzIwOGJkOWQ3MDgxODlkNzk2ZWJhY2FiNmRkMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Kv8LeyZwQpAykm0ftZ2iuU5xbfIjO18Al88DB4To7N4) Almost wasted my 39 account paint as 90% paint failed

i think it’s because of two reasons. first, the tournament hasn’t started yet (so there’s no canvas to paint on). and second, once the tournament starts, you have to wait for the 'I AM INEVITABLE' popup to show up so the canvas can be reset.

**Comment by cryptoknightsz** [comment]
Ok, i'll wait until start of round 2
Another ques, why random template json is empty

**Comment by Dellenoam** [comment]
Cause you need to manually fill it if you want to set specific templates, otherwise it will set a random one (not from file)

**Comment by Dellenoam** [comment]
Also about this problem. There are two options here

1. There's something wrong with your NotPixel account.
2. There is simply nothing to color on the template. A situation occurs when several users simultaneously paint one available pixel at the same time
