### ISSUE TITLE
BUG: Wrong Sleep At Night Time 

### ISSUE THREAD

**Issue by deyman12** [Dellenoam/NotPixelBot#21]
it's 5 PM right now, still evening, but why is the 'sleep at night' time already starting? my country uses the UTC+7 or GMT+7 timezone. i think you should keep this in mind since many countries have significant time differences.

![image](https://github.com/user-attachments/assets/0ee75b11-9ac2-4817-be93-9ef88e649e85)

**Comment by Dellenoam** [comment]
I did the fix, is this problem still being observed now? Make sure you have the latest version of the bot (do git pull)

**Comment by deyman12** [comment]
> I did the fix, is this problem still being observed now? Make sure you have the latest version of the bot (do git pull)

yes, bug fixed!! thank you!
