### ISSUE TITLE
paint coordinate accuracy

### ISSUE THREAD

**Issue by Usernameusernamenotavailbleisnot** [Dellenoam/NotPixelBot#29]
not paint at correct coordinates, out of template coordinates
in logging it is indeed successful but not paint according to template

**Comment by Dellenoam** [comment]
I need more info/screenshot of the problem

**Comment by Usernameusernamenotavailbleisnot** [comment]
![image](https://github.com/user-attachments/assets/52284753-1237-4345-b13d-4df92f2c2ef2)

im edditing your script only change logging for debug not function

i used the dogs template and it came out of the dogs coordinates

**Comment by Dellenoam** [comment]
Why do you think so? I can see that each of these pixels is not out of its coordinates
