### ISSUE TITLE
Multiple running 

### ISSUE THREAD

**Issue by RyomenRR** [Dellenoam/NotPixelBot#7]
Can you add option for 1by1 which is good for painting (saying from previous script)

**Comment by Dellenoam** [comment]
I don't understand what you mean and what script are you talking about?

**Comment by RyomenRR** [comment]
Like all accounts running at same time causes many incorrect pixels so I
used to have a script which allows me to select to run single thread or
multi thread

**Comment by RyomenRR** [comment]
![Screenshot_2024-11-23-06-40-53-674_com termux](https://github.com/user-attachments/assets/1ea1a0bb-5f54-4b33-bbbd-b96105e7ef22)

If only 1 account will run at a time that won't create this issue ig

**Comment by RyomenRR** [comment]
![IMG_20241123_111411_533](https://github.com/user-attachments/assets/ab0a41be-fbe1-4418-a01a-f3ffdfa2c54b)
![IMG_20241123_111411_659](https://github.com/user-attachments/assets/d0610572-9105-42ca-9219-e70559f5e9f6)


If single account run at single time then next account that will be okay because old script has same issue like this with multi thread

**Comment by Dellenoam** [comment]
Done
